### PR TITLE
only owner creates unshake chat card

### PR DESCRIPTION
**Pull request by bloy**
Add a check to prevent n unshake chat cards from being created where n
is the number of users logged in.

### CODE REVIEW

**Comment by javierriveracastro** [comment]
I wonder why no one said nothing about this...

**Comment by javierriveracastro** [comment]
But with this merge no card is shown for NPCs...

**Comment by javierriveracastro** [comment]
I changed it so it only the first GM creates the card.

**Comment by bloy** [comment]
Oops I thought I tested with an NPC also. Sorry about that. Thanks for fixing my fix.

**Pull request merged**
