### PR TITLE
Add attribute selector type

### PR DESCRIPTION
**Pull request by bloy**
Addresses #330 

* Add attribute selector type
* Add support for actions in the attribute card

### CODE REVIEW

**Comment by bloy** [comment]
There's some code duplication here, since I mostly copy-pasted from the skill card code for handling actions, so if you want me to try to clean that up let me know.

**Comment by javierriveracastro** [comment]
Creating a pseudo item with attributes... that's a neat idea.

Cleaning the duplicate code could be a good idea (or not), I need to check how skill.js works.

You are also exposing (more) the need to refactor ```check_selector```

Great work.

**Comment by bloy** [comment]
Looking at it the next morning, what I was thinking of as duplicated code is really the similarity between the new `roll_attribute` and the existing `roll_skill`. I might try to make something common between the two, or I can leave it if you think it's fine how it is.

Hmm. Refactoring `check_selector`... into a mini-function per selector type maybe?

**Comment by javierriveracastro** [comment]
I'm not really sure, I thinked about a class with a method named for each rule, but at the end I believe that this was more complicated to read. Some rules share functionality, just a couple of lines, but maybe it can be reused.

Maybe I'm just overengineering it, but the truth is that I don't like it and its getting bigger each update.

**Comment by bloy** [comment]
I was looking at `roll_skill`, `roll_item`, and `roll_attribute` and I feel like they're all JUST different enough that trying to put them together doesn't make sense. So I'm happy with this one as is if you are.

I may do another PR as a spike to refactor `check_selector` and see what you think. I think you're right that it's going to be either the if/else thing it is now, or a class of tiny functions. Both of which have their own different gross aspects.

**Comment by javierriveracastro** [comment]
You can try, but just changing it to a class instead of a lots of ifs or a case is not really an improvement. Merging this anyway.

**Comment by javierriveracastro** [comment]
Intellij only complains twice, one is the duplicate code (expected), but it is also suggesting to await for run_macros in line 222.

AFAIK this will make no difference at all. Maybe if there is an error in the macro it will be better reported, not sure about it.

**Comment by bloy** [comment]
I'm just fumbling around in javascript, tbh. You'd know better than me if it makes a difference if we wait for the macros to complete before the roll function completes. I don't feel like that matters either, but it also probably wouldn't hurt anything.

Thanks for accepting!

**Pull request merged**
