### PR TITLE
Update skill_card.js

### PR DESCRIPTION
**Pull request by TheLaslo**
address tokens without an actor in gangup calculation, also simplified the data gather

### CODE REVIEW

**Comment by javierriveracastro** [comment]
I pulled it for the data consolidation, but I don't get it.

Here you find the tokens without actor adjacent to the target:

```js
        tokensWithoutActor = canvas.tokens.placeables.filter(t =>
            t.id !== attacker.id
            && t.actor == null
            && withinRange(target, t, itemRange)
        );
```

But this value is never used, except inside this if

```js
        if (!attacker || !target) {
            console.log("BetterRolls 2: Unable to calculate gangUp because some tokens do not have an actor", tokensWithoutActor, attacker, target)
            return 0;
        }
```

But this if will always be false, because if it were true this one, that is way before (first line of the function) would have been shot.

```js
    if (!attacker || !target) {
        console.log("BetterRolls 2: Trying to calculate gangup with no token", attacker, target)
        return 0;
    }
```

So unless I'm not looking at it right, your code just does nothing.

**Comment by TheLaslo** [comment]
I agree with you.  I meant to change that condition to check the count.

**Comment by javierriveracastro** [comment]
How do you add a token without an actor?

I want to try another way (use optional chaining or ?.),

**Comment by TheLaslo** [comment]
In my case I had added a token previously.  Only at the time I wasn't in
the habit of dragging from actor tab, instead I dragged from the
compendium.  Each time you do that a copy of the actor is created in the
actor tab.  When I was done with those tokens in the scene I had deleted
the tokens from the actor tab, but hadn't deleted the tokens from the
scene.  Now when the scene is loaded those tokens do not have an actor.

**Pull request merged**
