### PR TITLE
grid based range calc

### PR DESCRIPTION
**Pull request by TheLaslo**
code to add the setting and use different range calc method if selected

### CODE REVIEW

**Comment by javierriveracastro** [comment]
There are two problems here.

The most important one is that you deleted Spanish, Catalan and German translations XDDDD... I assume this is a mistake and it should be easy to revert.

The second one is that you didn't make any allowance for altitude. Is that expected? You want differences in altitude to work different than differences in the grid? Or was that unintended?

**Comment by TheLaslo** [comment]
1. I removed the languages after Salieri told me Weblate would take care of those.

2. I reviewed that and the height imo would already be grid units, it is a column without going through any diagonals.

**Comment by javierriveracastro** [comment]
1. You don't need to translate or add the strings, but you should not delete the files.
2. 
3. Nope. It will also use Pythagoras to calculate the height diference. It is not about units, it is about not using geometry (i.e. counting diagonal distance bad). To keep it consistent with the other rules, someone 5 squares far, at height 4 should still be 5 spaces far. But whatever you want, as I said this doesn't really make sense to me, so if you (and people paying like you) feels that height should use pythagoras I'm fine with that.

**Comment by TheLaslo** [comment]
Ok, I'm sorry about the files.  I wasn't trying to delete them, just remove my changes to them.  How would I go about doing that or should I leave that to you?

**Comment by javierriveracastro** [comment]
Don't worry about the files. Do you want the patch merged as it is, or do you want to try to tackle the altitude thing?

**Comment by TheLaslo** [comment]
I think altitude is ok.  Merge would be great.  Thanks!

**Pull request merged**
