### PR TITLE
Update some actions to be single choice

### PR DESCRIPTION
**Pull request by steveculshaw**
Update some actions to be single choice

so far illumination, multi-action, desperate attack and called shot

### CODE REVIEW

**Comment by javierriveracastro** [comment]
Multi action can't be single choice. Unless we move run out of there you should be able to select both run and two actions for example. Also gm_actions don't support single choices.

**Comment by steveculshaw** [comment]
I thought I'd move Run out into situational ?

**Comment by javierriveracastro** [comment]
I didn't see it in the changes. I will look at it better when I merge it.

**Comment by steveculshaw** [comment]
Just checked, and the two multiple actions are in multiaction group and ran is in situational group

**Pull request merged**
