### PR TITLE
Add generic power modifiers

### PR DESCRIPTION
**Pull request by steveculshaw**
Copying over the generic power modifiers, based on the code in Savage Pathfinder Enhanced

`https://github.com/brunocalado/savage-pathfinder-enhanced/blob/main/scripts/br_ppcommon.js`

### CODE REVIEW

**Comment by javierriveracastro** [comment]
They need translation support, but I'd add it afterwards.

Thanks.

**Comment by steveculshaw** [comment]
@javierriveracastro 
Sorry, I only know English :-(

**Comment by javierriveracastro** [comment]
No, not the translation itself. You should enable the translators to do it. Check power-generic-modifiers.js and en.json now and you will see what I mean.

**Comment by javierriveracastro** [comment]
They can now use Weblate to translate the strings to another languages.

**Comment by steveculshaw** [comment]
> No, not the translation itself. You should enable the translators to do it. Check power-generic-modifiers.js and en.json now and you will see what I mean.

Ah ha ... I see what you mean !

**Pull request merged**
